.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH windrose-tui 1  "windrose-tui " 
.SH NAME
windrose\-tui \- Open the interactive dashboard (default)
.SH SYNOPSIS
\fBwindrose\-tui\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Open the interactive dashboard (default)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
