.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH windrose-doctor 1  "windrose-doctor " 
.SH NAME
windrose\-doctor \- Check health, guide setup, and suggest performance fixes
.SH SYNOPSIS
\fBwindrose\-doctor\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Check health, guide setup, and suggest performance fixes
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
